- name: Install required packages for AWS CLI
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Check if AWS CLI is already installed
  command: aws --version
  register: awscli_check
  ignore_errors: yes
  changed_when: false

- name: Download AWS CLI v2 installer
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
  when: awscli_check.rc != 0

- name: Unzip AWS CLI installer
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes
  when: awscli_check.rc != 0

- name: Install AWS CLI v2
  command: /tmp/aws/install
  when: awscli_check.rc != 0

- name: Clean up installer files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/awscliv2.zip
    - /tmp/aws
  when: awscli_check.rc != 0