- name: Install required system packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - curl
      - python3-pip

- name: Install Docker from Amazon extras
  shell: amazon-linux-extras install docker -y

- name: Start docker
  systemd:
    name: docker
    state: started
    enabled: yes
  when: ansible_virtualization_type != "docker"
  ignore_errors: yes

- name: Add ec2-user to docker group
  user:
    append: yes
    groups: docker
    user: "{{ item }}"
  loop:
    - ec2-user
    - "{{ github_user }}"

- name: Install amazon-ecr-credential-helper (manual install for Amazon Linux)
  get_url:
    url: https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.6.0/linux-amd64/docker-credential-ecr-login
    dest: /usr/local/bin/docker-credential-ecr-login
    mode: '0755'