- name: Install required system packages
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - amazon-ecr-credential-helper

- name: Create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce

- name: Start docker
  service:
    name: docker
    state: started
  when: ansible_virtualization_type != "docker"

- name: Add ubuntu user to docker group
  user:
    append: yes
    groups: docker
    user: "{{ item }}"
  loop:
    - ubuntu
    - "{{ github_user }}"