name: Test Playbooks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Make test script executable
      run: chmod +x test-playbooks.sh
    
    - name: Run test playbooks
      run: ./test-playbooks.sh